# Database Secrets for MSA Learning Platform
# 데이터베이스 연결 정보를 위한 Secret 리소스

---
# RDS PostgreSQL 연결 정보
apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
  namespace: backend
  labels:
    app.kubernetes.io/name: postgres-credentials
    app.kubernetes.io/part-of: eks-msa-learning
type: Opaque
data:
  # Base64 인코딩된 값들 (실제 운영시에는 AWS Secrets Manager 사용)
  # 기본값: username=dbadmin, password=changeme123!, host=localhost, port=5432
  username: ZGJhZG1pbg==
  password: Y2hhbmdlbWUxMjMh
  host: ${RDS_ENDPOINT_BASE64}
  port: NTQzMg==
  database: bXNhbGVhcm5pbmc=
  
---
# Catalog Service용 데이터베이스 연결 정보
apiVersion: v1
kind: Secret
metadata:
  name: catalog-db-credentials
  namespace: backend
  labels:
    app.kubernetes.io/name: catalog-db-credentials
    app.kubernetes.io/part-of: eks-msa-learning
    app.kubernetes.io/component: catalog-service
type: Opaque
data:
  # DATABASE_URL for FastAPI
  database_url: ${CATALOG_DATABASE_URL_BASE64}
  db_host: ${RDS_ENDPOINT_BASE64}
  db_port: NTQzMg==
  db_name: Y2F0YWxvZ19kYg==
  db_user: ZGJhZG1pbg==
  db_password: Y2hhbmdlbWUxMjMh

---
# Order Service용 데이터베이스 연결 정보
apiVersion: v1
kind: Secret
metadata:
  name: order-db-credentials
  namespace: backend
  labels:
    app.kubernetes.io/name: order-db-credentials
    app.kubernetes.io/part-of: eks-msa-learning
    app.kubernetes.io/component: order-service
type: Opaque
data:
  # Spring Boot DataSource 설정
  spring_datasource_url: ${ORDER_DATABASE_URL_BASE64}
  spring_datasource_username: ZGJhZG1pbg==
  spring_datasource_password: Y2hhbmdlbWUxMjMh
  db_host: ${RDS_ENDPOINT_BASE64}
  db_port: NTQzMg==
  db_name: b3JkZXJfZGI=

---
# Redis 연결 정보
apiVersion: v1
kind: Secret
metadata:
  name: redis-credentials
  namespace: backend
  labels:
    app.kubernetes.io/name: redis-credentials
    app.kubernetes.io/part-of: eks-msa-learning
type: Opaque
data:
  # Redis 연결 정보 (ElastiCache)
  redis_host: ${REDIS_ENDPOINT_BASE64}
  redis_port: NjM3OQ==
  redis_url: ${REDIS_URL_BASE64}
  # Redis 비밀번호 (ElastiCache에서 AUTH 사용시)
  redis_password: ""

---
# S3 접근을 위한 서비스별 설정
apiVersion: v1
kind: Secret
metadata:
  name: s3-credentials
  namespace: backend
  labels:
    app.kubernetes.io/name: s3-credentials
    app.kubernetes.io/part-of: eks-msa-learning
type: Opaque
data:
  # S3 버킷 정보
  s3_bucket_name: ${S3_BUCKET_NAME_BASE64}
  s3_region: YXAtbm9ydGhlYXN0LTE=
  # IRSA 사용시 AWS 자격증명은 불필요하지만 애플리케이션 호환성을 위해 유지
  aws_access_key_id: ""
  aws_secret_access_key: ""

---
# Frontend 네임스페이스용 S3 Secret
apiVersion: v1
kind: Secret
metadata:
  name: s3-credentials
  namespace: frontend
  labels:
    app.kubernetes.io/name: s3-credentials
    app.kubernetes.io/part-of: eks-msa-learning
type: Opaque
data:
  s3_bucket_name: ${S3_BUCKET_NAME_BASE64}
  s3_region: YXAtbm9ydGhlYXN0LTE=
  aws_access_key_id: ""
  aws_secret_access_key: ""