apiVersion: v1
kind: ConfigMap
metadata:
  name: application-config
  namespace: backend
  labels:
    app: application-config
data:
  # 서비스 URL 설정
  frontend-url: "https://eks-msa.example.com"
  api-url: "https://eks-msa.example.com/api"
  catalog-service-url: "http://catalog-service.backend.svc.cluster.local:8000"
  order-service-url: "http://order-service.backend.svc.cluster.local:8080"
  
  # AWS 설정
  aws-region: "ap-northeast-2"
  s3-bucket-name: "eks-msa-file-storage"
  
  # CORS 설정
  allowed-origins: "https://eks-msa.example.com,https://api.eks-msa.example.com"
  
  # 로깅 설정
  log-level: "INFO"
  
  # 캐시 설정
  cache-ttl: "3600"
  
  # 애플리케이션 설정
  max-file-size: "10485760"  # 10MB
  session-timeout: "1800"    # 30분
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: application-config
  namespace: frontend
  labels:
    app: application-config
data:
  # API 설정
  api-url: "https://eks-msa.example.com/api"
  
  # 환경 설정
  environment: "production"
  
  # 기능 플래그
  enable-file-upload: "true"
  enable-monitoring-dashboard: "true"
  
  # UI 설정
  app-title: "EKS MSA Learning Platform"
  theme: "default"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: monitoring-config
  namespace: monitoring
  labels:
    app: monitoring-config
data:
  # Prometheus 설정
  scrape-interval: "30s"
  evaluation-interval: "30s"
  
  # Grafana 설정
  grafana-admin-user: "admin"
  
  # 알람 설정
  alert-manager-webhook: "https://hooks.slack.com/services/YOUR/SLACK/WEBHOOK"
  
  # 메트릭 보존 기간
  metrics-retention: "15d"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: logging-config
  namespace: monitoring
  labels:
    app: logging-config
data:
  # Fluent Bit 설정
  fluent-bit-config: |
    [SERVICE]
        Flush         1
        Log_Level     info
        Daemon        off
        Parsers_File  parsers.conf
        HTTP_Server   On
        HTTP_Listen   0.0.0.0
        HTTP_Port     2020

    [INPUT]
        Name              tail
        Path              /var/log/containers/*.log
        Parser            docker
        Tag               kube.*
        Refresh_Interval  5
        Mem_Buf_Limit     50MB
        Skip_Long_Lines   On

    [FILTER]
        Name                kubernetes
        Match               kube.*
        Kube_URL            https://kubernetes.default.svc:443
        Kube_CA_File        /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        Kube_Token_File     /var/run/secrets/kubernetes.io/serviceaccount/token
        Kube_Tag_Prefix     kube.var.log.containers.
        Merge_Log           On
        Keep_Log            Off
        K8S-Logging.Parser  On
        K8S-Logging.Exclude Off

    [OUTPUT]
        Name                cloudwatch_logs
        Match               *
        region              ap-northeast-2
        log_group_name      /aws/eks/cluster/logs
        log_stream_prefix   eks-msa-
        auto_create_group   true

  parsers-config: |
    [PARSER]
        Name   docker
        Format json
        Time_Key time
        Time_Format %Y-%m-%dT%H:%M:%S.%L
        Time_Keep   On