# Catalog Service Deployment
# Python FastAPI 기반 상품 카탈로그 서비스를 위한 Kubernetes Deployment

apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-service
  namespace: backend
  labels:
    app.kubernetes.io/name: catalog-service
    app.kubernetes.io/part-of: eks-msa-learning
    app.kubernetes.io/component: catalog
    app.kubernetes.io/version: "1.0.0"
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: catalog-service
  template:
    metadata:
      labels:
        app.kubernetes.io/name: catalog-service
        app.kubernetes.io/part-of: eks-msa-learning
        app.kubernetes.io/component: catalog
        app.kubernetes.io/version: "1.0.0"
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9090"
        prometheus.io/path: "/metrics"
    spec:
      serviceAccountName: catalog-service-sa
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      initContainers:
      - name: db-migration
        image: ${ECR_REGISTRY}/eks-msa-learning/catalog-service:latest
        command: ['python', '-m', 'alembic', 'upgrade', 'head']
        env:
        # 데이터베이스 연결 정보 (Secret에서 가져옴)
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: catalog-db-secret
              key: database-url
        envFrom:
        - configMapRef:
            name: catalog-service-config
        - configMapRef:
            name: common-config
      containers:
      - name: catalog-service
        image: ${ECR_REGISTRY}/eks-msa-learning/catalog-service:latest
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 8000
          protocol: TCP
        - name: metrics
          containerPort: 9090
          protocol: TCP
        env:
        - name: PORT
          value: "8000"
        - name: METRICS_PORT
          value: "9090"
        # 데이터베이스 연결 정보 (Secret에서 가져옴)
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: catalog-db-secret
              key: database-url
        - name: DATABASE_HOST
          valueFrom:
            secretKeyRef:
              name: catalog-db-secret
              key: host
        - name: DATABASE_PORT
          valueFrom:
            secretKeyRef:
              name: catalog-db-secret
              key: port
        - name: DATABASE_NAME
          valueFrom:
            secretKeyRef:
              name: catalog-db-secret
              key: database
        - name: DATABASE_USER
          valueFrom:
            secretKeyRef:
              name: catalog-db-secret
              key: username
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: catalog-db-secret
              key: password
        # Redis 연결 정보 (Secret에서 가져옴)
        - name: REDIS_HOST
          valueFrom:
            secretKeyRef:
              name: redis-secret
              key: host
        - name: REDIS_PORT
          valueFrom:
            secretKeyRef:
              name: redis-secret
              key: port
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: redis-secret
              key: password
              optional: true
        envFrom:
        - configMapRef:
            name: catalog-service-config
        - configMapRef:
            name: common-config
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
          successThreshold: 1
        readinessProbe:
          httpGet:
            path: /health/ready
            port: http
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
          successThreshold: 1
        startupProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 15
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 30
          successThreshold: 1
        volumeMounts:
        - name: tmp-volume
          mountPath: /tmp
        - name: app-logs
          mountPath: /app/logs
      volumes:
      - name: tmp-volume
        emptyDir: {}
      - name: app-logs
        emptyDir: {}
      nodeSelector:
        kubernetes.io/arch: amd64
      tolerations:
      - key: "node.kubernetes.io/not-ready"
        operator: "Exists"
        effect: "NoExecute"
        tolerationSeconds: 300
      - key: "node.kubernetes.io/unreachable"
        operator: "Exists"
        effect: "NoExecute"
        tolerationSeconds: 300
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app.kubernetes.io/name
                  operator: In
                  values:
                  - catalog-service
              topologyKey: kubernetes.io/hostname
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            preference:
              matchExpressions:
              - key: node.kubernetes.io/instance-type
                operator: In
                values:
                - t3.medium
                - t3.large