# Order Service
# 주문 서비스를 위한 Kubernetes Service

apiVersion: v1
kind: Service
metadata:
  name: order-service
  namespace: backend
  labels:
    app.kubernetes.io/name: order-service
    app.kubernetes.io/part-of: eks-msa-learning
    app.kubernetes.io/component: order
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "http"
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-path: "/actuator/health"
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-interval: "30"
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-timeout: "5"
    service.beta.kubernetes.io/aws-load-balancer-healthy-threshold: "2"
    service.beta.kubernetes.io/aws-load-balancer-unhealthy-threshold: "3"
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 8080
    targetPort: http
    protocol: TCP
  - name: management
    port: 8081
    targetPort: management
    protocol: TCP
  selector:
    app.kubernetes.io/name: order-service
  sessionAffinity: None
---
# Order Service용 ServiceMonitor (Prometheus 메트릭 수집용)
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: order-service-metrics
  namespace: backend
  labels:
    app.kubernetes.io/name: order-service-metrics
    app.kubernetes.io/part-of: eks-msa-learning
    app.kubernetes.io/component: monitoring
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: order-service
  endpoints:
  - port: management
    path: /actuator/prometheus
    interval: 30s
    scrapeTimeout: 10s
  namespaceSelector:
    matchNames:
    - backend